name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: cdk deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/my-githubactions-role
          aws-region: ap-northeast-1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: CDK package install
        run: npm ci

      - name: install redoc-cli
        run: npm install -g redoc-cli

      - name: build openapi.html
        run: mkdir redoc-cli.out && redoc-cli bundle lambda_src/openapi.yml -o redoc-cli.out/index.html

      - name: output html
        run: cat redoc-cli.out/index.html

      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: |
          npm run cdk diff

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: |
          npm run cdk deploy

      - name: api document deploy
        if: contains(github.event_name, 'push')
        run: |
          aws s3 cp redoc-cli.out/index.html s3://${{ secrets.S3_BUCKET_NAME }}/
